name = "Modpack De Mis Amigos"
author = "Vegetta"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91bc6c3891cc78dbfbd3e206d8647016873819e2a326e03ffc99fa5239e88ecb"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
