name = "Modpack De Mis Amigos"
author = "Vegetta"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d59883662362f3ccc1900ec5fc86c5d9e7ba7f7517177ab5989806854e3ec42"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
