name = "Modpack De Mis Amigos"
author = "Vegetta"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5f19e55b9219f0413097e7953b8f0d134d69e7909add164ac7f5425e2e24182"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
